In [68]:
import sqlite3

def update_experiment_view(db_path='../cem_results.db'):
    """
    Drops the existing experiment_summary view and recreates it 
    with the updated metrics schema including the testset column.
    """
    # Define the SQL script
    sql_script = """
    DROP VIEW IF EXISTS experiment_summary;

    CREATE VIEW experiment_summary AS
    SELECT 
        r.dataset,
        r.entity, 
        r.model_type,
        r.train_size, 
        r.seed, 
        r.lm,
        m.pollution, 
        m.iteration, 
        m.testset,
        m.f1_score,
        m.precision,
        m.recall,
        m.is_final,
        r.run_id,
        r.timestamp
    FROM metrics m
    JOIN runs r ON m.run_id = r.run_id;
    """

    try:
        # Establish connection
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        # Execute the script (handles multiple statements)
        cursor.executescript(sql_script)
        
        conn.commit()
        print("View 'experiment_summary' has been updated successfully.")
        
    except sqlite3.Error as e:
        print(f"An error occurred: {e}")
        
    finally:
        if conn:
            conn.close()

# Run the update

# Check per Run_ID

In [ ]:


import sqlite3
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Connection
conn = sqlite3.connect('../cem_results.db')
update_experiment_view()

run_id = '9764503_1'

try:
    summary_query = f"""
        SELECT * FROM metrics WHERE run_id = '{run_id}' AND testset = 'test' ORDER BY "entity" desc 
    """
    
    # Execute and load into DataFrame
    df = pd.read_sql_query(summary_query, conn)

    df_filtered = df.drop(columns=['num_pairs'])
    display(df_filtered)

finally:
    conn.close()

# print(df_baseline.to_csv())

View 'experiment_summary' has been updated successfully.

,run_id,entity,pollution,iteration,is_final,testset,precision,recall,f1_score,runtime
0,9764478_2,name,high,0,1,test,0.953,0.883,0.917,245.213450
1,9764478_2,movie,high,0,1,test,0.953,0.749,0.839,322.037508

In [73]:


import sqlite3
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Connection
conn = sqlite3.connect('../cem_results.db')
update_experiment_view()

try:
    summary_query = f"""
        SELECT * FROM experiment_summary  ORDER BY "timestamp"  desc 
    """
    
    # Execute and load into DataFrame
    df = pd.read_sql_query(summary_query, conn)

    df_filtered = df.drop(columns=["dataset", "lm", "testset", "is_final", "run_id", "timestamp"])
    display(df_filtered)

finally:
    conn.close()

# print(df_baseline.to_csv())

View 'experiment_summary' has been updated successfully.

,entity,model_type,train_size,seed,pollution,iteration,f1_score,precision,recall
0,2026-04-16 15:30:47,baseline,1.0,30,high,0,0.839,0.953,0.749
1,2026-04-16 15:30:47,baseline,1.0,30,high,0,0.917,0.953,0.883
2,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.830,0.972,0.724
3,2026-04-16 16:32:16,1,1.0,30,high,0,0.830,0.972,0.724
4,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.830,0.972,0.724
...,...,...,...,...,...,...,...,...,...
217,2026-04-16 16:22:52,1,1.0,30,high,3,0.909,0.937,0.883
218,2026-04-16 16:13:28,baseline,1.0,10,high,3,0.971,0.978,0.965
219,2026-04-16 16:22:52,1,1.0,10,high,3,0.971,0.978,0.965
220,2026-04-16 16:13:28,baseline,1.0,20,high,3,0.952,0.928,0.978
221,2026-04-16 16:22:52,1,1.0,20,high,3,0.952,0.928,0.978

In [72]:
import sqlite3
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Connection
conn = sqlite3.connect('../cem_results.db')
update_experiment_view()

target_entity = "movie"
target_size = 1.0
target_seed = 42
target_pollution = "high"


try:

    summary_query = f"""
        SELECT * FROM experiment_summary 
        WHERE entity = '{target_entity}' AND
        train_size = '{target_size}' AND

        pollution = '{target_pollution}'
        ORDER BY "timestamp" DESC
    """
    
    # Execute and load into DataFrame
    df_results = pd.read_sql_query(summary_query, conn)
    display(df_results)

finally:
    conn.close()


results_filtered = df_results.drop(columns=["dataset", "model_type", "lm", "testset", "is_final", "run_id", "timestamp"])
print(results_filtered.to_csv())

View 'experiment_summary' has been updated successfully.

Empty DataFrame
Columns: [dataset, entity, model_type, train_size, seed, lm, pollution, iteration, testset, f1_score, precision, recall, is_final, run_id, timestamp]
Index: []

,entity,train_size,seed,pollution,iteration,f1_score,precision,recall

In [ ]:


import sqlite3
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# 1. Connection
conn = sqlite3.connect('../cem_results.db')
update_experiment_view()

try:
    summary_query = f"""
        SELECT * FROM experiment_summary WHERE model_type = 'baseline' ORDER BY "timestamp"  desc LIMIT 20
    """
    
    # Execute and load into DataFrame
    df_baseline = pd.read_sql_query(summary_query, conn)

    baseline_filtered = df_baseline.drop(columns=["dataset", "lm", "testset", "is_final", "run_id", "timestamp"])
    display(baseline_filtered)

finally:
    conn.close()

# print(df_baseline.to_csv())

View 'experiment_summary' has been updated successfully.
Successfully retrieved data for 0 runs.

,entity,model_type,train_size,seed,pollution,iteration,f1_score,precision,recall
0,2026-04-16 15:30:47,baseline,1.0,30,high,0,0.839,0.953,0.749
1,2026-04-16 15:30:47,baseline,1.0,30,high,0,0.917,0.953,0.883
2,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.830,0.972,0.724
3,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.830,0.972,0.724
4,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.830,0.972,0.724
5,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.919,0.951,0.889
6,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.919,0.951,0.889
7,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.919,0.951,0.889
8,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.882,0.961,0.815
9,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.870,0.933,0.815
10,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.879,0.964,0.808
11,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.872,0.941,0.812
12,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.873,0.969,0.794
13,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.869,0.957,0.797
14,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.556,0.400,0.910
15,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.020,0.021,0.019
16,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.696,0.567,0.902
17,2026-04-16 16:17:39,baseline,1.0,20,high,0,0.903,0.898,0.908
18,2026-04-16 16:17:39,baseline,1.0,10,high,0,0.914,0.932,0.897
19,2026-04-16 16:17:39,baseline,1.0,30,high,0,0.026,0.250,0.014

In [71]:
target_entity = "movie"
target_size = 1.0
target_seed = 42
target_pollution = "high"

# Filter the dataframe
mask = (
    # (results_filtered["entity"] == target_entity) &
    (results_filtered["train_size"] == target_size) &
    (results_filtered["seed"] == target_seed) &
    (results_filtered["pollution"] == target_pollution)
)

display(results_filtered[mask])

# Filter the dataframe
mask = (
    # (results_filtered["entity"] == target_entity) &
    (baseline_filtered["train_size"] == target_size) &
    (baseline_filtered["seed"] == target_seed) &
    (baseline_filtered["pollution"] == target_pollution)
)

display(baseline_filtered[mask])



import pandas as pd

# Define the columns to match on
match_cols = ["train_size", "seed", "pollution", "entity"]

# Perform an inner join to align the rows
df_comparison = pd.merge(
    df_results, 
    df_baseline, 
    on=match_cols, 
    suffixes=('_res', '_base')
)

display(df_comparison)
# Now you can calculate differences, for example:
df_comparison['score_diff'] = df_comparison['f1_score_res'] - df_comparison['f1_score_base']
display(df_comparison)

Empty DataFrame
Columns: [entity, train_size, seed, pollution, iteration, f1_score, precision, recall]
Index: []

Empty DataFrame
Columns: [entity, model_type, train_size, seed, pollution, iteration, f1_score, precision, recall]
Index: []

Empty DataFrame
Columns: [dataset_res, entity, model_type_res, train_size, seed, lm_res, pollution, iteration_res, testset_res, f1_score_res, precision_res, recall_res, is_final_res, run_id_res, timestamp_res, dataset_base, model_type_base, lm_base, iteration_base, testset_base, f1_score_base, precision_base, recall_base, is_final_base, run_id_base, timestamp_base]
Index: []

[0 rows x 26 columns]

Empty DataFrame
Columns: [dataset_res, entity, model_type_res, train_size, seed, lm_res, pollution, iteration_res, testset_res, f1_score_res, precision_res, recall_res, is_final_res, run_id_res, timestamp_res, dataset_base, model_type_base, lm_base, iteration_base, testset_base, f1_score_base, precision_base, recall_base, is_final_base, run_id_base, timestamp_base, score_diff]
Index: []

[0 rows x 27 columns]